# -*- coding: utf-8 -*-
"""Estatística-Aula1-Exercícios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10caEC6Iin0_bejA3LmCbTovTUB_P2AYp

Escreva um comando utilizando a função print que informe seu primeiro nome, seu RA, o código da disciplina e o ano seguindo o formato: {nome} - {RA} - {código da disciplina} - {ano}. Observação: Não utilize o parâmetro sep.
"""

nome = "Ana"
RA = 248706
codigoDaDisciplina = "AS012TSN1"
ano = 2025

print(nome, end = " - ")
print(RA, end = " - ")
print(codigoDaDisciplina, end = " - ")
print(ano)

"""Escreva um programa que, dados três números inteiros, imprima o menor deles."""

numero1, numero2, numero3 = 10, 8, 2
print("O menor número é", min(numero1, numero2, numero3))

"""Escreva um programa que, dados três números inteiros, imprima os números em ordem crescente."""

numeros = [10, 8, 2]
print(sorted(numeros))

"""Escrever a seguinte equação, supondo que conhece as variáveis a, b, c."""



""" Escreva um código que calcule a hipotenusa de um triângulo retângulo, cujos catetos são 𝑎 = 6 e 𝑏 = 6."""

a = 6
b = 6

c = ((a ** 2) + (b ** 2)) ** 0.5
print(c)

"""O programa compara dois números, imprima "Os dois são iguais", "O maior número é o primeiro" ou "O maior número é o segundo"."""

numero1, numero2 = 11, 11

if numero1 == numero2:
  print("Os dois são iguais")
else:
  if numero1 > numero2:
     print("O maior número é o primeiro")
  else:
     print("O maior número é o segundo")